class Solution:
    def __init__(self):
        self.id = None
        self.uuid = None
        self.authorLogin = None
        self.authorName = None
        self.company = None
        self.name = None
        self.version = None
        self.summary = None
        self.tag1 = None
        self.tag2 = None
        self.tag3 = None
        self.subject1 = None
        self.subject2 = None
        self.subject3 = None
        self.displayOrder = None
        self.pictureUrl = None
        self.active = None
        self.modelType = None
        self.toolkitType = None
        self.starCount = None
        self.viewCount = None
        self.createdDate = None
        self.modifiedDate = None
        self.hasWeb =None
        self.deployStatus = None
        self.deployer = None
        self.deployDate = None
        self.k8sPort = None
        self.callCount = None
