FROM ubuntu/python3.6:0.0.9
WORKDIR /app
ENV LANG C.UTF-8
ADD . /app
RUN pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
EXPOSE 3330
CMD ["/usr/python3/bin/cubeai_model_runner", "model/"]

