FROM ubuntu/python-sk:3.0.0
WORKDIR /app
ENV LANG C.UTF-8
ADD . /app
RUN pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
EXPOSE 3330
CMD ["acumos_model_runner", "model/"]
