import {Route, Routes} from '@angular/router';
import {HomeComponent} from './home.component';
import {
    antennaMeasurementRoutes,
    antsBeesRoutes,
    artWordRoutes,
    audioClassifierRoutes,
    carPlateRoutes,
    cellphoneChangeRoutes,
    chineseOcrRoutes,
    chineseSummaryRoutes,
    coupletRoutes,
    demoRoutes,
    dimsimRoutes,
    exchangerateRoutes,
    faceCutRoutes,
    faceRecognitionRoutes,
    faceRecognizerRoutes,
    faceSwapRoutes,
    facialAgeRoutes,
    facialAge2Routes,
    facialEmotionRoutes,
    fincialEntityRoutes,
    genderAgeRoutes,
    googleTranslateRoutes,
    handwritingRoutes,
    idcardInfoRoutes,
    idcardNumberRoutes,
    idiomRoutes,
    imageColorizerRoutes,
    imageEnhancerRoutes,
    imageRectifyRoutes,
    imageStyleTransferRoutes,
    imagenetRoutes,
    imgclassifyRoutes,
    ltespeedRoutes,
    ocrRoutes,
    ocrWordcloudRoutes,
    opmRoutes,
    pinyinRoutes,
    poemWriterRoutes,
    qrcodeRoutes,
    sceneClassifyRoutes,
    sentimentRoutes,
    speechActRoutes,
    taocanRoutes,
    textCorrectRoutes,
    textGrapherRoutes,
    traintableRoutes,
    vehicleRoutes,
    weatherRoutes,
    wordcloudRoutes,
} from './';

const homeRoute: Route = {
    path: '',
    component: HomeComponent,
    data: {
        pageTitle: 'CubeAI能力开放应用示范',
    },
};

export const homeRoutes: Routes = [
    homeRoute,
    ...antennaMeasurementRoutes,
    ...antsBeesRoutes,
    ...artWordRoutes,
    ...audioClassifierRoutes,
    ...carPlateRoutes,
    ...cellphoneChangeRoutes,
    ...chineseOcrRoutes,
    ...chineseSummaryRoutes,
    ...coupletRoutes,
    ...demoRoutes,
    ...dimsimRoutes,
    ...exchangerateRoutes,
    ...faceCutRoutes,
    ...faceRecognitionRoutes,
    ...faceRecognizerRoutes,
    ...faceSwapRoutes,
    ...facialAgeRoutes,
    ...facialAge2Routes,
    ...facialEmotionRoutes,
    ...fincialEntityRoutes,
    ...genderAgeRoutes,
    ...googleTranslateRoutes,
    ...handwritingRoutes,
    ...idcardInfoRoutes,
    ...idcardNumberRoutes,
    ...idiomRoutes,
    ...imageColorizerRoutes,
    ...imageEnhancerRoutes,
    ...imageRectifyRoutes,
    ...imageStyleTransferRoutes,
    ...imagenetRoutes,
    ...imgclassifyRoutes,
    ...ltespeedRoutes,
    ...ocrRoutes,
    ...ocrWordcloudRoutes,
    ...opmRoutes,
    ...pinyinRoutes,
    ...poemWriterRoutes,
    ...qrcodeRoutes,
    ...sceneClassifyRoutes,
    ...sentimentRoutes,
    ...speechActRoutes,
    ...taocanRoutes,
    ...textCorrectRoutes,
    ...textGrapherRoutes,
    ...traintableRoutes,
    ...vehicleRoutes,
    ...weatherRoutes,
    ...wordcloudRoutes,
];
